service: opensourcery-aws-workshop
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  iam:
    role:
      name: role
      statements:
        - Effect: 'Allow'
          Resource: '*'
          Action: 'dynamodb:*'
          
functions:

  hello:
    handler: hello.handler
    events:
      - httpApi:
          path: /hello
          method: get

  newItem:
    handler: newItem.handler
    events:
      - httpApi:
          path: /create
          method: get

resources:
  Resources:
    TodoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: OpenSourceryTodoTable
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: noteId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: noteId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
